name: Deploy to S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

    
      - name: Build project
        run: npm run build
        
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exact-timestamps dist --exclude ".git/*"
        env:
          AWS_S3_BUCKET: www.nxlbeautybar.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1

      - name: Fix MIME types
        run: |
          # JavaScript
          aws s3 cp dist/ s3://www.nxlbeautybar.com/ --recursive --content-type "text/javascript" --exclude "*" --include "*.js"
          # CSS
          aws s3 cp dist/ s3://www.nxlbeautybar.com/ --recursive --content-type "text/css" --exclude "*" --include "*.css"
          # HTML
          aws s3 cp dist/ s3://www.nxlbeautybar.com/ --recursive --content-type "text/html" --exclude "*" --include "*.html"
          # JSON
          aws s3 cp dist/ s3://www.nxlbeautybar.com/ --recursive --content-type "application/json" --exclude "*" --include "*.json"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
